# Usa una imagen base de Go
FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

# Copia el código fuente
COPY src/ .

# Construye la aplicación
RUN go build -o main .

# Expone el puerto en el que la aplicación escuchará
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["./main"]