version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: apiflask-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api_flask
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apigo-web
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_DATABASE: api_flask

networks:
  mynetwork:
    driver: bridge
