version: '3.8'

services:
  db:
    image: mysql:8.0  # Actualiza a una versión más reciente
    container_name: apiflask-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api_flask  # Puedes definir una base de datos por defecto si lo deseas
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/mysql  # Persistencia de datos

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apigo-web
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_DATABASE: api_flask

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data: